title = "Zola Bear+ Theme"
base_url = "https://marcal.cc/zola-bearplus"
description = "Minimalistic yet a bit featureful theme for the Zola static site generator."

compile_sass = true
build_search_index = false

taxonomies = [
  {name = "tags", feed = true},
]

[markdown]
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
  { theme = "OneHalfDark", filename = "syntax-theme-dark.css" },
  { theme = "OneHalfLight", filename = "syntax-theme-light.css" },
]

[extra]
post_date_format="%d %B, %Y"
list_date_format="%d %b, %Y"
theme_toggle = true
fa_icons = true
render_latex = true
echarts = true

[[extra.main_menu]]
name = "Blog"
url = "@/blog/_index.md"

[[extra.main_menu]]
name = "GitHub"
icon = "fa-brands fa-github"
url = "https://github.com/salcc/zola-bearplus"
